name: local
variables:
  - name: base_url
    value: http://localhost:4000
  - name: graphql_url
    value: http://localhost:4000/graphql
  - name: api_url
    value: http://localhost:4000/api
  - name: auth_cookie
    value: better-auth.session_token=QkcBhadpkqa6nlge2EW5sSEIex29rnTW.ir0R14FfqxZDCOQse%2FS5QMz8mSuZib2YGGOCsZ19lU4%3D
