name: local
variables:
  - name: base_url
    value: http://localhost:4000
  - name: graphql_url
    value: http://localhost:4000/graphql
  - name: api_url
    value: http://localhost:4000/api
  - name: auth_cookie
    value: better-auth.session_token=URp8QlHKGGtaGV8BGAhQilKIjJa0Lq7b.Wtd3vxlyE2szTxWL%2FqOGtgmq9AIc9o%2BBVxnCzfAyrlE%3D
